### ISSUE TITLE
Auto-detect serviceContext.service on GCP

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-logging-bunyan#135]
The Error Reporting API requires a `serviceContext.service` when reporting errors.  Thus, if an error is logged by this library, but `serviceContext.service` is not specified, the error will not be reported to the Error Reporting console.

For applications deployed to GCP, the service should be automatically detected if possible.

See PR #122 and issue #121 for more information.

**Comment by ofrobots** [comment]
Need to wait for pre-req in `logging`: https://github.com/googleapis/nodejs-logging/pull/400.

**Comment by ofrobots** [comment]
This can proceed once there is a new release of `logging`.

**Comment by DominicKramer** [comment]
@JustinBeckwith Can we get a release of `logging` so that this PR can proceed?

**Comment by JustinBeckwith** [comment]
Oh, we're trying.... https://github.com/googleapis/nodejs-logging/pull/423

**Comment by DominicKramer** [comment]
Looks like 4.5.0 is out now.  Thanks :smiley:

**Comment by ofrobots** [comment]
How blocked on https://github.com/googleapis/nodejs-logging/issues/429.

**Comment by bcoe** [comment]
@ofrobots is this still blocked, looks like 429 was closed?

**Comment by ofrobots** [comment]
Now blocked on https://github.com/googleapis/nodejs-logging/issues/442.

**Comment by ofrobots** [comment]
Decided to unblock by continuing to use synthetic types.
