### ISSUE TITLE
Unhandled exception from gRPC for request size

### ISSUE THREAD

**Issue by matanh-tzmedical** [googleapis/nodejs-logging-bunyan#14]
When trying to load test the our kubernetes stack by sending thousands of requests to our exposed endpoint I get this error which crashes the Node app:

```{ Error: Request payload size exceeds the limit: 10485760 bytes. at /var/www/node_modules/grpc/src/client.js:554:15 code: 3, metadata: Metadata { _internal_repr: {} } }```

It seems like the 1MB buffering that the `@google-cloud/logging` library is supposed to be doing is not happening.

#### Environment details

  - OS: Google Cloud Container Cluster - Ubuntu Latest Node image
  - Node.js version: Docker public image - node:6.10.3
  - npm version: 3.10.10
  - @google-cloud/logging-bunyan version: 0.7.0

#### Steps to reproduce

  1. Enable stackdriver logging on a Google Cloud Kubernetes app.
  2. Log thousands of requests as fast as possible.

**Comment by murgatroid99** [comment]
This is a gRPC thing. By default, gRPC sets a limit on the size of (serialized) messages that can be sent or received. This can be modified with the channel arguments `"grpc.max_receive_message_length"` and `"grpc.max_send_message_length"`, which are defined [here](https://github.com/grpc/grpc/blob/baa14a975ef92ee6fb301f0e684f56f18f2c55a7/include/grpc/impl/codegen/grpc_types.h#L147). A value of `-1` allows for messages of unlimited size in both cases.

**Comment by ofrobots** [comment]
So it seems that the google-cloud/common-grpc library [sets the defaults](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/25af76e2f79ad3a1da9e859aefd9a6db942c2aea/packages/common-grpc/src/service.js#L136) to:

```js
var GRPC_SERVICE_OPTIONS = {
  // RE: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1991
  'grpc.max_send_message_length': -1, // unlimited
  'grpc.max_receive_message_length': -1, // unlimited

  // RE: https://github.com/grpc/grpc/issues/8839
  // RE: https://github.com/grpc/grpc/issues/8382
  // RE: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1991
  'grpc.initial_reconnect_backoff_ms': 5000
};
```

So, that is already as expected. It would seem that somehow this is not taking effect.

**Comment by ofrobots** [comment]
@stephenplusplus @lukesneeringer It seems that logging may be using the google-gax path. would this config in common-grpc apply at all?  I don't see google-gax doing anything with the size limits.

**Comment by ofrobots** [comment]
Repro

```

const bunyan = require('bunyan');
const LB = require('@google-cloud/logging-bunyan');

const lb = new LB({projectId: 'a real project id'});

const logger = bunyan.createLogger({
  name: 'my-service',
  streams: [
    lb.stream()
  ]
});

for (let i = 0; i < 100; i++) {
  logger.info({buffer: new Int8Array(56150)}, 'shields at 99%');
}
```

**Comment by stephenplusplus** [comment]
google-gax doesn't set any of these defaults, as far as I know. It should probably just copy the settings in common-grpc.

For now, this should work:

```js
const lb = new LB({
  projectId: 'a real project id',
  'grpc.max_send_message_length': -1,
  'grpc.max_receive_message_length': -1,
  'grpc.initial_reconnect_backoff_ms': 5000
});
```

**Comment by ofrobots** [comment]
@stephenplusplus that didn't work actually.

I think this issue belongs upstream in logging. Or perhaps more generally in all gax based in libraries given that there are known issues that caused us to customize the config in common-grpc. It doesn't make sense that we are using different network config for common-grpc libraries vs. gax based libraries.

I am going to move this issue to logging for now.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/gax-nodejs#157
