### ISSUE TITLE
Incorrect GCE instance_id

### ISSUE THREAD

**Issue by catiepg** [googleapis/nodejs-logging-bunyan#148]
#### Environment details

  - OS: CentOS on a GCE instance
  - Node.js version: 8.9.3
  - npm version: yarn 1.4.0
  - `@google-cloud/logging-bunyan` version: 0.8.2

#### Steps to reproduce

Logging from within a GCE instance consistently produces wrong `instance_id` in `resource.labels`, e.g. `2554270933530966500` while the actual ID is `2554270933530966670`. This makes using the GCP Console inconvenient where the logs are filtered by `instance_id` by default. Also while the project is correctly filled, the zone is missing:

```
resource: {
  labels: {
    instance_id:  "2554270933530966500"    
    project_id:  "my-project"    
    zone:  ""    
  }
  type:  "gce_instance"   
}
```

I suspect the `instance_id` issue has something to do with https://github.com/googleapis/gcp-metadata/pull/74 but since the zone is missing as well there might be more to it.

**Comment by ofrobots** [comment]
This should be fixed through the [v3.0.3 release](https://github.com/googleapis/nodejs-logging/releases/tag/v3.0.3) of `@google-cloud/logging`. If you install dependencies from again, that should be automatically picked up as per the semver range for this module.

I'm going to close this. Please comment and we'll re-open if you still have problems.

**Comment by catiepg** [comment]
Thank you for the quick resolution! When can we expect `@google-cloud/logging@3.0.3` to be published to npm?

**Comment by JustinBeckwith** [comment]
Apologies in the delay - we're actively working on getting that out the door today 🤞

**Comment by ofrobots** [comment]
It turned out that we needed to release `@google-cloud/logging@4.x` which requires a re-release of this module to pick up. We are currently working on getting the latter out of the door. Thanks you for your patience!

**Comment by catiepg** [comment]
Updated to `@google-cloud/logging-bunyan@0.9.2` and it works like a charm! Thanks!
