### ISSUE TITLE
Express middleware does not nest stackdriver entries

### ISSUE THREAD

**Issue by avishnyak** [googleapis/nodejs-logging-bunyan#172]
#### Environment details

  - OS: Ubuntu
  - Node.js version: 10.x
  - yarn version: 1.10.1
  - `@google-cloud/logging-bunyan` version: "^0.9.4"

#### Steps to reproduce

1. Add middleware to express pipeline.
```js
  async function StartServer() {
    const { mw } = await lb.express.middleware({
      logName: 'assets',
    })

    const app = express()

    // Enable this to get the proper IP from X-Forwarded-For headers
    app.enable('trust proxy')

    // Do not send X-Powered-By header
    app.disable('x-powered-by')

    // Install the logging middleware. This ensures that a Bunyan-style `log`
    // function is available on the `request` object. Attach this as one of the
    // earliest middleware to make sure that log function is available in all the
    // subsequent middleware and routes.
    app.use(mw)

    /* routes here */

    return app
  }
```

2. Log multiple entries against the request

```js
    req.log.info({
      httpRequest: {
        status: statusCode,
        requestUrl: req.url,
        requestMethod: req.method,
        remoteIp: req.ip,
        userAgent: req.headers['user-agent'],
        responseSize: res.get('Content-Length') || res._contentLength || 0,
        latency: {
          seconds: Math.floor(nanos / 1e9),
          nanos: Math.floor(nanos % 1e9),
        },
      },
    }, path)
    req.log.info(req.headers)
    req.log.info(`Timings: ${timings}`)
```

Unlike the documentation states, the log entries are not nested.  They do have the same ```trace``` and ```insertId```.

<img width="1519" alt="screen shot 2018-10-09 at 12 53 33 pm" src="https://user-images.githubusercontent.com/6599079/46695969-deb1f300-cbc5-11e8-84ed-e6a3b34d4c8c.png">

**Comment by ofrobots** [comment]
Hi @avishnyak! Which environment (GCE, GKE, GAE, GCF, Locally, elsewhere) are you running the application?

Secondly, for the screenshot you posted above, which Logs did you enable in the Logging UI? For example this screenshot has the 'request_log' log enabled:

![image](https://user-images.githubusercontent.com/79017/46714189-18f3b280-cc0f-11e8-952f-85a43ae8539f.png)

**Comment by avishnyak** [comment]
Hi @ofrobots,

The application is runnnig in GKE and I have the "GKE Container, <cluster_name>, default" in the first dropdown and the name of my service (assets) selected in the second dropdown.

**Comment by ofrobots** [comment]
I am going to merge this into #159, which should address the issue. @avishnyak  In the meanwhile, you can workaround by creating a separate parent log stream where you would write the `httpRequest` log entries.
