### ISSUE TITLE
Address system test failures <EOM>

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-logging-bunyan#267]

**Comment by DominicKramer** [comment]
Logging errors should report the errors to the error reporting service.  The system tests pulls the errors reported from the error reporting console to ensure that is the case.

Many changes have been made to try to make this pull more reliable based on the fact that it can take some time for errors to appear in the error reporting console.  However, the pulling mechanism is still not reliable enough to support consistent system test success.

I think we should just verify in the system tests that when a log at log level error is created, the appropriate payload used in calls to `@google-cloud/logging` has the error log level.

**Comment by JustinBeckwith** [comment]
👋 just a heads up - bumping the priority to p1.  I don't think something can be both release blocking and a p2 at the same time :)

**Comment by ofrobots** [comment]
@DominicKramer I am not sure if this really needs to be labelled release-blocking.
