### ISSUE TITLE
Heads up: logging on kubernetes broken in @google-cloud/logging 1.1.2

### ISSUE THREAD

**Issue by bkw** [googleapis/nodejs-logging-bunyan#31]
Since we have spent an evening searching in the wrong space, here's a mention of googleapis/nodejs-logging#68, maybe it helps somebody. 

Workaround for the time being seems to be to pin googleapis/nodejs-logging to 1.1.1.

**Comment by bkw** [comment]
googleapis/nodejs-logging#53 seems to the main issue tracking this,

**Comment by DominicKramer** [comment]
Thank you for opening this issue.

**Comment by ofrobots** [comment]
Folks, the issue in @google-cloud/nodejs-logging has been fixed via googleapis/nodejs-logging#81 and released via v1.1.5 of that library. That version should get picked up when you reinstall your node_modules. Please give that a short and report back if there are still issues. Thanks!

**Comment by ofrobots** [comment]
Closing as fixed. Please reply if there are still issues.
