### ISSUE TITLE
K8s metadata missing from `resource.labels` object

### ISSUE THREAD

**Issue by EricSEkong** [googleapis/nodejs-logging-bunyan#347]
#### Description 
Log entries are missing container specific information: container_name, instance_id, pod_id...
those fields appear as empty strings in Stackdrive console

```
labels: {
   cluster_name:  "cluster_name"    
   container_name:  ""    
   instance_id:  ""    
   namespace_id:  "namespace_id"    
   pod_id:  ""    
   project_id:  "project_id"    
   zone:  ""    
  }
```
#### Environment details

  - Docker Image: node:10.16.3-alpine running on GKE
  - Node.js version: 10.16.3
  - npm version:
  - `@google-cloud/logging-bunyan` version: 1.2.2

#### Steps to reproduce

```
const streams = [];
const loggingBunyan = new LoggingBunyan();
streams.push(loggingBunyan.stream('debug'));
const logger = bunyan.createLogger({
  name, level, streams, serializers
});
```

**Comment by jasperkuperus** [comment]
I posted a solution for having `severity` work with `winston`, using `stdout` (so not with a transport provided by this package). I did a quick smoke test and saw that this also works on `bunyan` when you just supplement your JSON with a `severity`. A working `winston` example can be found here: https://github.com/googleapis/nodejs-logging-winston/issues/386#issuecomment-602195498

**Comment by atrain0789** [comment]
+1

**Comment by typicalnerd** [comment]
+1

**Comment by nicoleczhu** [comment]
Closing as this fix is via [this PR](https://github.com/googleapis/nodejs-logging/pull/1070), releasing next week.

**Comment by EricSEkong** [comment]
thanks @nicoleczhu 🚀

**Comment by LaloLoop** [comment]
Quick update for anyone else wondering. You need to set up `automountServiceAccountToken: true` in your service account, if using a custom one. I'm using a custom one because the default service account cannot write to GCP Loggin for some reason. Also, pass the CONTAINER_NAME in the logs; as the code explains this must be supplied by the developer.
