### ISSUE TITLE
RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Log ingestion requests' and limit 'Log ingestion requests per minute' of service 'logging.googleapis.com'

### ISSUE THREAD

**Issue by bharatdevparmar** [googleapis/nodejs-logging-bunyan#446]
#### Environment details

  - OS: Windows 10
  - Node.js version: 10.18.0
  - npm version: 6.13.4
  - `@google-cloud/logging-bunyan` version: 2.0.3

#### Steps to reproduce

  1. Write logs more than "Cloud Logging API Limit of 60,000".
  2. When logging quota limit reached, node server crashing because of "Quota exceeded" error.

Is there any way to get these errors using callback or handled it using bunyan library. so it will not crash node server?

Thanks!

**Comment by nicoleczhu** [comment]
We'll address this in a future sprint. We agree that logging library quota limit shouldn't crash your entire app

**Comment by rokon12** [comment]
Is there any update regarding this issue?

**Comment by losalex** [comment]
Sorry for delay. @rokon12 - recently we implemented an ability to supply a global callback in base nodejs-logging library - the fix it [1225](https://github.com/googleapis/nodejs-logging/pull/1225). Once the fix is released, we can expose an ability to supply a global callback in `LoggingBunyan`.

**Comment by losalex** [comment]
@rokon12, thanks for your patience - I believe this issue should be resolved by [#597](https://github.com/googleapis/nodejs-logging-bunyan/pull/597). The solution is to provide a global callback which could be used to process responses and catch any errors. There is a sample [here](https://github.com/googleapis/nodejs-logging-bunyan#error-handling-with-a-default-callback) which could be used as reference on how such callback can be provided. I am closing this issue for now and please feel free to reopen/comment in case if you have more concerns or feedback.
