### ISSUE TITLE
Opentelemetry integration

### ISSUE THREAD

**Issue by Mistic92** [googleapis/nodejs-logging-bunyan#448]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Now, suggested tracing solution on gcp for node is to use [opentelemetry ](https://cloud.google.com/trace/docs/setup) but this bunyan logger is integrating only with gcp trace library. 
 **Describe the solution you'd like**
Handle integration with Opentelemetry the same as with gcp trace library

**Comment by nicoleczhu** [comment]
Hi @Mistic92 , folks, this is releasing today. It detects trace/span from the traceparent header. But it's [a custom impl](https://github.com/googleapis/nodejs-logging/blob/master/src/context.ts) within nodejs-logging, so it may lack additional features that the opentelemetry-tracing library supports.

Let me know how it goes and if there's anything we can fix/patch!
