### ISSUE TITLE
logging-{winston,bunyan} should integrate well with Logging UI and with Error Reporting

### ISSUE THREAD

**Issue by gaofanmichael** [googleapis/nodejs-logging-bunyan#5]
_From @ofrobots on February 13, 2017 18:5_

Originally raised here https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1977#issuecomment-278743604.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1989_

**Comment by gaofanmichael** [comment]
_From @danoscarmike on February 27, 2017 22:29_

@ofrobots can you confirm that this is does not change the surface?

**Comment by gaofanmichael** [comment]
_From @ofrobots on February 28, 2017 0:24_

@danoscarmike Do you mean if this is a semver major change on the `logging` API?

Actually the concrete pull request fixing this issue is here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1997

This does not affect the `logging` module API at all. It is a behaviour change in how the `logging-winston` and `logging-bunyan`modules format messages, but this still isn't a semver major change. These said modules are still marked 'experimental' so this should be okay.

**Comment by danoscarmike** [comment]
Thanks @gaofanmichael.  To be honest I can't recall the context of my question but nothing sounds alarming :)

**Comment by ofrobots** [comment]
Agree with @gaofanmichael disposition above. This has been addressed and can be closed now.
