### ISSUE TITLE
Failing system test

### ISSUE THREAD

**Issue by simonz130** [googleapis/nodejs-logging-bunyan#505]
Test is failing with these errors:

`
<testcase classname="express middleware global logger" name="should properly write log entries" time="30.009">
<failure>Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/test-middleware-express.js) Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/test-middleware-express.js) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)</failure>
</testcase>
<testcase classname="express middleware request logging middleware" name="should write request correlated log entries" time="30.004">
<failure>Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/test-middleware-express.js) Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/test-middleware-express.js) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)</failure>
</testcase>
</testsuite>
`

**Comment by nicoleczhu** [comment]
I was able to get the tests passing locally and verify nightly is passing again: https://g3c.corp.google.com/results/invocations/654dea76-53ad-4654-a5ee-0553c9503119

chalking this one to OMG issue as well
