### ISSUE TITLE
Make logs more Google log entry compliant

### ISSUE THREAD

**Issue by VGavara** [googleapis/nodejs-logging-bunyan#515]
As exposed in [Structured Logging](https://cloud.google.com/logging/docs/structured-logging?hl=en) and [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) documentation, there is a certain expected behaviour when logging to Google and that can be summarized as:

- If the log is a text message, store it in the `textPayload` field.
- If the log is a JSON payload, do the same in the `jsonPayload` field.

Apart of etiquette matters, it helps a lot when searching in logs, since you clearly know what is the field storing the info you're looking for and therefore you can set the correct log filter.

Now `nodejs-logging-bunyan` is storing all the user information in the `jsonPayload` field, mixed with information that is not strictly set by the user but inherited from bunyan (fields `level`, `time`, `v`, `pid`, `name` and `hostname`). Even just logging a text message, that in theory should be stored in the log field `textPayload`, it is being stored in `jsonPayload`.

This behaviour seems to be agains what Google etiquette states, creates a difference between the logs coming from `nodejs-logging-bunyan` and other sources that, in last term, makes their management harder. However I find it easy to correct:

1. by removing the unused fields (specifically `v`, `pid`, `name` and `hostname`) as exposed [here](https://github.com/trentm/node-bunyan/issues/462). I understand this shouldn't be done internally by `nodejs-logging-bunyan` (maybe they were storing user information) but by the user after creating a `LoggingBunyan` object.
2. by removing bunyan needed fields once used, specifically by deleting fields `time` and `level` once consumed in the function `formatEntry_`
3. by deciding, once all the `record` fields are processed in the function `formatEntry_`, if `record` contains just a message, and therefore it must be logged as `textPayload`, or still exist user custom fields and therefore the record must be logged as `jsonPayload`. `textPayload` logging is achieved by calling the function `stackDriverLog.entry` with a string as second argument, whereas `jsonPayload` logging is achieved by calling the same function with an object as second argument.

I made some tests applying that exposed and I get logs as expected, what makes easier their management. It's a pity that the first point (removing unused fields) had to be performed externally to the library (or at least so I understand). If it could be done inside the library, no bunyan-like trace would arrive to Stackdriver.

I wonder if this matter has already been proposed. I've made a quick search of closed issues with no luck.

**Comment by nicoleczhu** [comment]
Hi @VGavara , you can filter either text or json payloads, i.e. if you wanted payloads containing the string "pubsub" you can do: 
`textPayload:"pubsub" OR jsonPayload:"pubsub"`. See [advanced queries here](https://cloud.google.com/logging/docs/view/advanced-queries#advanced_logs_query_syntax). 

As you said, we won’t provide a user level option to remove those fields within this library, since these are its intentional features. For a more customizable logging experience, there’s [Nodejs-logging](https://www.npmjs.com/package/@google-cloud/logging) package.
