### ISSUE TITLE
Log levels not accounted for in Log Viewer

### ISSUE THREAD

**Issue by ddykhoff** [googleapis/nodejs-logging-bunyan#59]
#### Environment details

  - OS: Windows 10
  - Node.js version: 10.0.0
  - npm version: 6.0.1
  - `@google-cloud/logging-bunyan` version: 0.8.1

#### Steps to reproduce
```
import { LoggingBunyan } from '@google-cloud/logging-bunyan';
import * as bunyan from 'bunyan';

const cloudLogger: LoggingBunyan = new LoggingBunyan();

export default bunyan.createLogger({
  name: 'messaging',
  streams: [
    {stream: process.stdout, level: 'info'},
    cloudLogger.stream('info')
  ]
});
```

Use Application Default Credentials.
Deploy to App Engine flex environment.

Resulting logs in Log Viewer are all put under the 'any' log level (i.e. `logger.info`, `logger.warn`, `logger.error` are ignored). Error objects logged to `logger.error` do appropriately show up in Error Reporting correctly.

![image](https://user-images.githubusercontent.com/10856592/39941730-1632e222-5523-11e8-9d78-d2b64612f228.png)

**Comment by ofrobots** [comment]
Thanks for reporting. Confirmed bug. This was reported internally earlier this week as well.

It seems that we are missing the `severity` field missing from the LogEntry :

```
{
 insertId:  "..........pX_9QkRCK0wQgqvSWRgW9B"  
 jsonPayload: {
  hostname:  "localhost"   
  level:  30   
  message:  "bunyan.info"   
  name:  "my-bunyan-name"   
  pid:  6   
  time:  "Tue May 08 2018 04:15:48 GMT+0000 (UTC)"   
  v:  0   
 }
 logName:  "-obfuscated-"  
 receiveTimestamp:  "2018-05-08T04:15:50.923833984Z"  
 resource: {
  labels: {
   module_id:  "test-cloud-logging"    
   project_id:  "jasonco-play"    
   version_id:  "20180507t210614"    
  }
  type:  "gae_app"   
 }
 timestamp:  "2018-05-08T04:15:48.401000022Z"  
}
```

We will be looking at this shortly.

**Comment by QuestionAndAnswer** [comment]
I'm seeing that fix has been merged, but I'm still receiving version with wrong line even after fresh installation.

![image](https://user-images.githubusercontent.com/6842709/40248670-5124c7d6-5ad9-11e8-8a12-d9010c40e25e.png)
 
Could you please verify published package?

**Comment by ofrobots** [comment]
Hi @QuestionAndAnswer we haven't published a release with this fix just. We will notify this thread once a release has been published.

**Comment by ofrobots** [comment]
The fix should be available via the [v0.8.2 release](https://github.com/googleapis/nodejs-logging-bunyan/releases/tag/v0.8.2).

**Comment by QuestionAndAnswer** [comment]
Thanks. Working.

**Comment by dieguezz** [comment]
Hi, sorry but i am still having problems with this. Maybe i am doing something wrong:
<img width="1117" alt="captura de pantalla 2018-08-16 a las 10 25 27" src="https://user-images.githubusercontent.com/1161455/44197435-dba70300-a13e-11e8-86b7-5f8961a66fb7.png">

```
const bunyan = require('bunyan')

// Imports the Google Cloud client library for Bunyan (Node 6+)
const { LoggingBunyan } = require('@google-cloud/logging-bunyan')

// Creates a Bunyan Stackdriver Logging client
const loggingBunyan = new LoggingBunyan()

// Create a Bunyan logger that streams to Stackdriver Logging
// Logs will be written to: "projects/YOUR_PROJECT_ID/logs/bunyan_log"
const logger = bunyan.createLogger({
  // The JSON payload of the log as it appears in Stackdriver Logging
  // will contain "name": "my-service"
  name: 'my-service',
  // log at 'info' and above
  streams: [
    // Log to the console
    { stream: process.stdout },
    // And log to Stackdriver Logging
    loggingBunyan.stream(),
  ],
})

module.exports = {
  logger,
}

```

```
logger.error('ERROR')
```

**Comment by samcfinan** [comment]
I think this issue has reemerged. Using `v3.0.1` and experiencing the same behavior as the above poster. All logs appear as `default`.

Initialization:

```
const streams: Stream[] = [{ stream: process.stdout, level: 'info' }]

const logger = bunyan.createLogger({
  name: 'invintory-api',
  streams,
  serializers: stdSerializers,
})

if (envIsHosted()) {
  const gcpLogger = new LoggingBunyan()
  streams.push(gcpLogger.stream('info'))
}

export default logger
```

Example log:
```
{
  "insertId": "l4a45qxpqq7rroz7m",
  "jsonPayload": {
    "method": "GET",
    "requestID": "771e850b-8132-41a9-99ab-30650c34a626",
    "v": 0,
    "msg": "",
    "path": "/health",
    "pid": 37,
    "level": 30,
    "name": "redacted",
    "body": {},
    "query": {},
    "hostname": "redacted"
  },
  "resource": {
    "type": "gae_app",
    "labels": {
      "module_id": "default",
      "version_id": "20210207t022501",
      "zone": "",
      "project_id": "redacted"
    }
  },
  "timestamp": "2021-02-07T18:53:24.450Z",
  "labels": {
    "compute.googleapis.com/resource_id": "redacted",
    "appengine.googleapis.com/instance_name": "redacted",
    "compute.googleapis.com/zone": "us-central1-c",
    "compute.googleapis.com/resource_name": "redacted"
  },
  "logName": "redacted",
  "receiveTimestamp": "2021-02-07T18:53:29.468290729Z"
}
```
