### ISSUE TITLE
Logging to stdout in Cloud Run creates a JSON object as "message"

### ISSUE THREAD

**Issue by losalex** [googleapis/nodejs-logging-bunyan#643]
When enabling structured logging to STDOUT, received structured JSON payload containing an extra "message" key with the original logged message, as well as a "metadata" key of an empty object.

**Comment by sytranvn** [comment]
![image](https://github.com/googleapis/nodejs-logging-bunyan/assets/13009812/4af51449-2c7a-4df8-8055-6f437544b8f2)
I'm using Cloud Run and `logging-bunyan@v4.2.2` and it's logging message object when enable `redirectToStdout`.

[This document](https://cloud.google.com/nodejs/docs/reference/logging-winston/latest#alternative-way-to-ingest-logs-in-google-cloud-managed-environments) says `useMessageField` is always `true` but #644  tests expect it to be `false`. 
> Note that there is also a useMessageField option which controls if "message" field is used to store structured, non-text data inside jsonPayload field when redirectToStdout is set. By default useMessageField is always true.
