### ISSUE TITLE
Wrong example of logger.info({msg:..

### ISSUE THREAD

**Issue by ffeu** [googleapis/nodejs-logging-bunyan#66]
Hi, apparently there's a wrong example in the README.md.

```
logger.info({
  msg: 'Bunyan log entry with custom trace field',
  [LoggingBunyan.LOGGING_TRACE_KEY]: 'custom-trace-value'
});
```

With me, it only worked with ```message:```.

Cheers,

**Comment by steren** [comment]
I can reproduce the issue.

It seems we need to fix 2 things:

1. [Bunyan's log API](https://github.com/trentm/node-bunyan#log-method-api) seems to prefer the message being as a second argument.

2. `LoggingBunyan.LOGGING_TRACE_KEY` is `undefined` for me 


The following snippet works for me: `logger.info({'trace': 'custom-trace-value'}, 'my message');`

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  Yes, it looks like the docs need to be updated, and we need to determine why `LoggingBunyan.LOGGING_TRACE_KEY` is `undefined`.  It shouldn't be necessary to use the `'logging.googleapis.com/trace'` string directly.
