### ISSUE TITLE
Recommended way for middleware + typescript

### ISSUE THREAD

**Issue by gugahoi** [googleapis/nodejs-logging-bunyan#674]
Just wondering what the recommended way to use this package's middleware with typescript. Is there a type to use for the request so that the compiler can understand the `log` calls? Currently I get the following error:

![Screen Shot 2022-11-23 at 2 37 03 pm](https://user-images.githubusercontent.com/355877/203464742-e9e2fdb5-7b28-4880-a326-a3a58d3abbbd.png)

Do I need to extend the type definitions myself?

**Comment by yfr** [comment]
A little late but maybe of help still: 

```typescript
import {Logger} from '@google-cloud/logging-bunyan/build/src/middleware/express';

declare global {
  namespace Express {
    export interface Request {
      log: Logger;
    }
  }
}
```

This extends the request object of typescript globally.

**Comment by cindy-peng** [comment]
Hi @gugahoi, yes you can extend the type definition yourself to use this middleware in typescript. At this moment, we don't export the extended Request type in this library.
