### ISSUE TITLE
Expose jsonFieldsToTruncate

### ISSUE THREAD

**Issue by seeARMS** [googleapis/nodejs-logging-bunyan#682]
It would be great to expose [jsonFieldsToTruncate](https://github.com/googleapis/nodejs-logging/pull/1177) in this library. I'd love to pass in a list of custom fields I use frequently, to ensure they get truncated.

I frequently log entries that do not get truncated, since they're nested in some custom entry. Thus, they get dropped.

Another reference: https://github.com/googleapis/nodejs-logging-bunyan/issues/524

**Comment by cindy-peng** [comment]
Hi @seeARMS, I have submitted a PR to enable custom fields truncation in this repo. Please let me know if you have any furthuer questions. Thank you!
