### ISSUE TITLE
Release new patch version to benefit from `d740098`

### ISSUE THREAD

**Issue by mpsq** [googleapis/nodejs-logging-bunyan#714]
It's all in the title, would it be possible to release a patch version of this package so downstream projects can benefit from https://github.com/googleapis/nodejs-logging-bunyan/commit/d74009850b316d57a686637f3b0242fa72339000 (which solves dependency hell problems)
Thank you :pray:

**Comment by mpsq** [comment]
cc. @daniel-sanche do you have any update on this?

**Comment by cindy-peng** [comment]
Hi @mpsq, sorry about the delayed response. We have triggered a new release [v5.0.1](https://github.com/googleapis/nodejs-logging-bunyan/releases/tag/v5.0.1) which includes commit https://github.com/googleapis/nodejs-logging-bunyan/commit/d74009850b316d57a686637f3b0242fa72339000. Thanks!
